import Foundation

/// Inline translations for running-program UI strings, voice cues, badges
/// and phase titles. We use these instead of NSLocalizedString for the
/// running-programs feature so we don't have to grow Localizable.xcstrings
/// by ~80 entries per language.
///
/// SwiftUI's `Text(LocalizedStringKey(key))` and our voice coach both call
/// `NSLocalizedString` under the hood, so we shadow that with our own table
/// via the `T()` helper.
enum ProgramStrings {
    /// Returns the translated value for a given key in the user's current
    /// language. Falls back to English, then the key itself.
    static func value(_ key: String, language: String) -> String {
        if let langTable = table[language], let v = langTable[key] { return v }
        if let en = table["en"], let v = en[key] { return v }
        return key
    }

    /// Convenience: uses the active LanguageManager language.
    static func value(_ key: String) -> String {
        value(key, language: LanguageManager.shared.selectedCode)
    }

    /// `["en": ["voice.walk": "Walk"], "es": [...]]`
    private static let table: [String: [String: String]] = [
        "en": en, "es": es, "fr": fr, "it": it, "pt-BR": ptBR,
    ]

    // MARK: - English

    private static let en: [String: String] = [
        // Programs — Walk to lose weight
        "program.walk.name": "Walk to Lose Weight",
        "program.walk.subtitle": "20-week walking program with progressive intensity",
        "program.walk.phase1.title": "Adapt to an active life",
        "program.walk.phase1.body": "Start your journey easily by walking. Activate your body and add walks to your daily routine.",
        "program.walk.phase2.title": "Calorie burner",
        "program.walk.phase2.body": "Follow a science-backed plan to lose weight. Walk longer and at a brisker pace each week.",
        "program.walk.phase3.title": "Burn faster",
        "program.walk.phase3.body": "Burn fat more efficiently, boost metabolism and trigger the afterburn effect.",
        "program.walk.goal1": "Add more walking to your lifestyle",
        "program.walk.goal2": "Feel happier and more active",
        "program.walk.goal3": "Build a lasting daily habit",

        // Programs — Run to lose weight
        "program.run.name": "Run to Lose Weight",
        "program.run.subtitle": "12-week walk-jog-run program for fat loss",
        "program.run.phase1.title": "Get moving",
        "program.run.phase1.body": "Build a base with walk-jog intervals so your body adapts safely.",
        "program.run.phase2.title": "Fat-burner intervals",
        "program.run.phase2.body": "Add running bursts that raise your metabolism and burn more fat after the session.",
        "program.run.phase3.title": "Run strong",
        "program.run.phase3.body": "Mix longer runs with sprints for the highest calorie burn.",
        "program.run.goal1": "Lose weight without losing motivation",
        "program.run.goal2": "Build the habit of running 3x/week",
        "program.run.goal3": "Improve cardiovascular health",

        // Programs — Running Academy
        "program.pace.name": "Running Academy",
        "program.pace.subtitle": "8-week tempo and interval training",
        "program.pace.phase1.title": "Tempo base",
        "program.pace.phase1.body": "Learn to hold a comfortable-hard pace and build cardio efficiency.",
        "program.pace.phase2.title": "Speed work",
        "program.pace.phase2.body": "Add structured intervals to raise your VO2 max and ceiling.",
        "program.pace.phase3.title": "Race-ready",
        "program.pace.phase3.body": "Sharpen with sprints and short bursts to drop your kilometre time.",
        "program.pace.goal1": "Run faster at every distance",
        "program.pace.goal2": "Build aerobic and anaerobic capacity",
        "program.pace.goal3": "Train like a real runner",

        // Programs — My first 5K
        "program.5k.name": "My First 5K",
        "program.5k.subtitle": "12-week couch-to-5K plan, walk to run",
        "program.5k.phase1.title": "Walk-run base",
        "program.5k.phase1.body": "Alternate walks and short jogs so your tendons and lungs adapt.",
        "program.5k.phase2.title": "Build the run",
        "program.5k.phase2.body": "Extend your jogs until you can run for 20+ minutes without stopping.",
        "program.5k.phase3.title": "Finish the 5K",
        "program.5k.phase3.body": "Cement the 30-minute run and finish your first 5K with a sprint.",
        "program.5k.goal1": "Run 5K nonstop in 12 weeks",
        "program.5k.goal2": "Develop a strong running habit",
        "program.5k.goal3": "Feel proud of finishing your first race distance",

        // Badges
        "badge.lowImpact": "Low impact",
        "badge.scienceBacked": "Science-backed",
        "badge.beginnerFriendly": "Beginner friendly",
        "badge.gradualDuration": "Gradual duration",
        "badge.fatBurning": "Fat burning",
        "badge.progressive": "Progressive",
        "badge.tempoTraining": "Tempo training",
        "badge.intervalScience": "Interval science",
        "badge.intermediate": "Intermediate",
        "badge.couchTo5k": "Couch to 5K",

        // Voice cues
        "voice.warmup": "warm-up",
        "voice.walk": "walk",
        "voice.briskWalk": "brisk walk",
        "voice.jog": "jog",
        "voice.run": "run",
        "voice.fastRun": "fast run",
        "voice.sprint": "sprint",
        "voice.cooldown": "cool down",
        "voice.rest": "rest",
        "voice.start": "Start with",
        "voice.now": "Now",
        "voice.halfway": "Halfway through. Keep it up.",
        "voice.finish": "Workout complete. Great job!",
        "voice.paused": "Workout paused.",
        "voice.resumed": "Resuming workout.",
        "voice.duration.minutes": "for %d minutes",
        "voice.duration.seconds": "for %d seconds",
        "voice.duration.minutesSeconds": "for %d minutes %d seconds",

        // UI strings
        "Walk & Run Programs": "Walk & Run Programs",
        "Lose weight · 5K · Pace · Voice coach": "Lose weight · 5K · Pace · Voice coach",
        "Pick a program and start today": "Pick a program and start today",
        "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.":
            "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.",
        "Introduction": "Introduction",
        "Progress": "Progress",
        "About the programs": "About the programs",
        "Expected results": "Expected results",
        "Your personalised plan": "Your personalised plan",
        "Scientific hybrid": "Scientific hybrid",
        "Walking · Jogging · Running": "Walking · Jogging · Running",
        "Start Now": "Start Now",
        "Day": "Day",
        "Day complete!": "Day complete!",
        "Save": "Save",
        "Discard": "Discard",
        "Finish session?": "Finish session?",
        "Save your progress for this day?": "Save your progress for this day?",
        "Endurance": "Endurance",
        "Speed": "Speed",
        "Next": "Next",
        "Start": "Start",
        "Finish": "Finish",
        "Total": "Total",
        "Completed": "Completed",

        // Plurals (printf style)
        "%lld-week program": "%lld-week program",
        "%lld days/week": "%lld days/week",
        "Week %lld · Day %lld": "Week %lld · Day %lld",
        "Week %lld": "Week %lld",
        "Weeks %lld-%lld": "Weeks %lld-%lld",
        "You finished week %lld, day %lld.": "You finished week %lld, day %lld.",

        // Settings
        "Voice Coach": "Voice Coach",
        "Vibration": "Vibration",
        "Voice & Vibration": "Voice & Vibration",

        // Sports catalog
        "Sports": "Sports",
        "Track any sport": "Track any sport",
        "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.":
            "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.",
        "Outdoor": "Outdoor",
        "Indoor": "Indoor",
        "Water": "Water",
        "Team & Racquet": "Team & Racquet",
        "GPS": "GPS",
        "Distance": "Distance",
        "Burned": "Burned",
        "Time": "Time",
        "Done": "Done",
        "Workout complete": "Workout complete",
        "Save this session to your history and Apple Health?":
            "Save this session to your history and Apple Health?",
        "Cancel": "Cancel",
        "Location is off": "Location is off",
        "Open Settings": "Open Settings",
        "Allow Location": "Allow Location",
        "Location access needed": "Location access needed",
        "PowerPump uses your location to trace your route and measure distance.":
            "PowerPump uses your location to trace your route and measure distance.",

        // Sport names
        "sport.cycling":        "Cycling",
        "sport.hiking":         "Hiking",
        "sport.skating":        "Skating",
        "sport.skiing":         "Skiing",
        "sport.snowboarding":   "Snowboarding",
        "sport.climbing":       "Climbing",
        "sport.golf":           "Golf",
        "sport.stationaryBike": "Stationary Bike",
        "sport.elliptical":     "Elliptical",
        "sport.treadmill":      "Treadmill",
        "sport.stairStepper":   "Stair Stepper",
        "sport.yoga":           "Yoga",
        "sport.pilates":        "Pilates",
        "sport.dance":          "Dance",
        "sport.boxing":         "Boxing",
        "sport.martialArts":    "Martial Arts",
        "sport.hiit":           "HIIT",
        "sport.rowing":         "Rowing",
        "sport.swimming":       "Swimming",
        "sport.openWaterSwim":  "Open Water Swim",
        "sport.surfing":        "Surfing",
        "sport.diving":         "Diving",
        "sport.paddleboard":    "Paddleboard",
        "sport.kayaking":       "Kayaking",
        "sport.tennis":         "Tennis",
        "sport.soccer":         "Soccer",
        "sport.basketball":     "Basketball",
        "sport.volleyball":     "Volleyball",
        "sport.baseball":       "Baseball",
        "sport.padel":          "Padel",

        // Sport detail / past-session UI
        "Your stats":               "Your stats",
        "sessions":                 "sessions",
        "Total time":               "Total time",
        "Avg Pace":                 "Avg Pace",
        "History":                  "History",
        "No sessions yet":          "No sessions yet",
        "Tap Start to log your first session.": "Tap Start to log your first session.",
        "Start session":            "Start session",

        // AI Route planner
        "route.title":        "AI Route",
        "route.subtitle":     "Let PowerPump plan a loop from where you are",
        "route.pickDistance": "Pick your distance",
        "route.generate":     "Generate my route",
        "route.generating":   "Building your route…",
        "route.regenerate":   "Try another route",
        "route.runThis":      "Run this route",
        "route.custom":       "Custom",
        "route.failed":       "Couldn't build a route here. Try a shorter distance or move to a street with paths.",
        "route.plannedLabel": "Planned route",
        "route.stageA":       "A",
        "route.stageB":       "B",
        "route.stageC":       "C",
        "route.km":           "km",
        "voice.route.start":  "Starting your route. Follow the blue line. Let's go!",
        "voice.route.stageB": "Great pace! You've reached stage B, the halfway point. Keep it up.",
        "voice.route.stageC": "Final stage. You're almost home, push to the finish!",
        "voice.route.finish": "Route complete. Amazing work!",
    ]

    // MARK: - Spanish

    private static let es: [String: String] = [
        "program.walk.name": "Caminar para adelgazar",
        "program.walk.subtitle": "Programa de 20 semanas para caminar con intensidad progresiva",
        "program.walk.phase1.title": "Adáptate a una vida activa",
        "program.walk.phase1.body": "Empieza fácilmente tu viaje andando. Activa el cuerpo e incorpora caminatas en tu rutina diaria.",
        "program.walk.phase2.title": "Quemador de calorías",
        "program.walk.phase2.body": "Sigue un programa científico para perder peso. Haz caminatas cada vez más largas y a ritmo más rápido.",
        "program.walk.phase3.title": "Quema más rápido",
        "program.walk.phase3.body": "Quema grasa más eficazmente, estimula el metabolismo y crea el efecto \"afterburn\".",
        "program.walk.goal1": "Incorpora más caminatas a tu estilo de vida",
        "program.walk.goal2": "Siéntete más feliz y activo",
        "program.walk.goal3": "Crea un hábito diario duradero",

        "program.run.name": "Correr para adelgazar",
        "program.run.subtitle": "Programa de 12 semanas andar-trotar-correr para perder grasa",
        "program.run.phase1.title": "Ponte en marcha",
        "program.run.phase1.body": "Crea una base con intervalos andar-trotar para que tu cuerpo se adapte sin riesgo.",
        "program.run.phase2.title": "Intervalos quemagrasa",
        "program.run.phase2.body": "Añade tramos de carrera que elevan el metabolismo y queman más grasa tras la sesión.",
        "program.run.phase3.title": "Corre con fuerza",
        "program.run.phase3.body": "Combina carreras más largas con sprints para el mayor gasto calórico.",
        "program.run.goal1": "Perder peso sin perder motivación",
        "program.run.goal2": "Crear el hábito de correr 3 veces por semana",
        "program.run.goal3": "Mejorar tu salud cardiovascular",

        "program.pace.name": "Academia Running",
        "program.pace.subtitle": "8 semanas de tempo y entrenamiento por intervalos",
        "program.pace.phase1.title": "Base de tempo",
        "program.pace.phase1.body": "Aprende a mantener un ritmo cómodo-fuerte y mejora tu eficiencia cardiovascular.",
        "program.pace.phase2.title": "Trabajo de velocidad",
        "program.pace.phase2.body": "Añade intervalos estructurados para subir tu VO2 max.",
        "program.pace.phase3.title": "Listo para correr",
        "program.pace.phase3.body": "Pule con sprints y series cortas para bajar tu tiempo por kilómetro.",
        "program.pace.goal1": "Correr más rápido en cualquier distancia",
        "program.pace.goal2": "Desarrollar capacidad aeróbica y anaeróbica",
        "program.pace.goal3": "Entrenar como un verdadero corredor",

        "program.5k.name": "Mi primer 5K",
        "program.5k.subtitle": "Plan de 12 semanas del sofá al 5K, de andar a correr",
        "program.5k.phase1.title": "Base de andar-correr",
        "program.5k.phase1.body": "Alterna caminatas y trotes cortos para que tu cuerpo se adapte.",
        "program.5k.phase2.title": "Construye el trote",
        "program.5k.phase2.body": "Extiende tus trotes hasta poder correr 20+ minutos sin parar.",
        "program.5k.phase3.title": "Termina los 5K",
        "program.5k.phase3.body": "Consolida los 30 minutos de carrera y termina tu primer 5K con un sprint.",
        "program.5k.goal1": "Correr 5K sin parar en 12 semanas",
        "program.5k.goal2": "Desarrollar un hábito sólido de correr",
        "program.5k.goal3": "Sentirte orgulloso de terminar tu primera distancia",

        "badge.lowImpact": "Impacto bajo",
        "badge.scienceBacked": "Eficacia demostrada",
        "badge.beginnerFriendly": "Apto para principiantes",
        "badge.gradualDuration": "Aumento gradual de duración",
        "badge.fatBurning": "Quema grasa",
        "badge.progressive": "Progresivo",
        "badge.tempoTraining": "Entrenamiento de tempo",
        "badge.intervalScience": "Ciencia del intervalo",
        "badge.intermediate": "Intermedio",
        "badge.couchTo5k": "Del sofá al 5K",

        "voice.warmup": "calentamiento",
        "voice.walk": "anda",
        "voice.briskWalk": "anda rápido",
        "voice.jog": "trota",
        "voice.run": "corre",
        "voice.fastRun": "corre rápido",
        "voice.sprint": "sprint",
        "voice.cooldown": "enfría",
        "voice.rest": "descansa",
        "voice.start": "Empieza con",
        "voice.now": "Ahora",
        "voice.halfway": "Mitad del intervalo. Sigue así.",
        "voice.finish": "Sesión completa. ¡Muy bien!",
        "voice.paused": "Sesión en pausa.",
        "voice.resumed": "Reanudando.",
        "voice.duration.minutes": "durante %d minutos",
        "voice.duration.seconds": "durante %d segundos",
        "voice.duration.minutesSeconds": "durante %d minutos %d segundos",

        "Walk & Run Programs": "Programas de andar y correr",
        "Lose weight · 5K · Pace · Voice coach": "Adelgazar · 5K · Ritmo · Voz coach",
        "Pick a program and start today": "Elige un programa y empieza hoy",
        "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.":
            "Sesiones guiadas por voz que adaptan andar, trotar y correr durante semanas para que progreses sin riesgo.",
        "Introduction": "Introducción",
        "Progress": "Progreso",
        "About the programs": "Acerca de los programas",
        "Expected results": "Resultados esperados",
        "Your personalised plan": "Tu programa personalizado",
        "Scientific hybrid": "Híbrido científico",
        "Walking · Jogging · Running": "Caminar · Trotar · Correr",
        "Start Now": "Empezar ahora",
        "Day": "Día",
        "Day complete!": "¡Día completado!",
        "Save": "Guardar",
        "Discard": "Descartar",
        "Finish session?": "¿Terminar la sesión?",
        "Save your progress for this day?": "¿Guardar tu progreso de este día?",
        "Endurance": "Resistencia",
        "Speed": "Velocidad",
        "Next": "Siguiente",
        "Start": "Inicio",
        "Finish": "Terminar",
        "Total": "Total",
        "Completed": "Completado",

        "%lld-week program": "Programa de %lld semanas",
        "%lld days/week": "%lld días/semana",
        "Week %lld · Day %lld": "Semana %lld · Día %lld",
        "Week %lld": "Semana %lld",
        "Weeks %lld-%lld": "Semanas %lld-%lld",
        "You finished week %lld, day %lld.": "Terminaste la semana %lld, día %lld.",

        "Voice Coach": "Voz coach",
        "Vibration": "Vibración",
        "Voice & Vibration": "Voz y vibración",

        "Sports": "Deportes",
        "Track any sport": "Registra cualquier deporte",
        "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.":
            "Elige un deporte para empezar una sesión. Los deportes al aire libre usan GPS. Todo se sincroniza con Apple Salud.",
        "Outdoor": "Aire libre",
        "Indoor": "Interior",
        "Water": "Agua",
        "Team & Racquet": "Equipo y raqueta",
        "GPS": "GPS",
        "Distance": "Distancia",
        "Burned": "Quemadas",
        "Time": "Tiempo",
        "Done": "Hecho",
        "Workout complete": "Sesión completa",
        "Save this session to your history and Apple Health?":
            "¿Guardar esta sesión en tu historial y Apple Salud?",
        "Cancel": "Cancelar",
        "Location is off": "Ubicación desactivada",
        "Open Settings": "Abrir Ajustes",
        "Allow Location": "Permitir ubicación",
        "Location access needed": "Necesita acceso a ubicación",
        "PowerPump uses your location to trace your route and measure distance.":
            "PowerPump usa tu ubicación para trazar tu ruta y medir distancia.",

        "sport.cycling":        "Ciclismo",
        "sport.hiking":         "Senderismo",
        "sport.skating":        "Patinaje",
        "sport.skiing":         "Esquí",
        "sport.snowboarding":   "Snowboard",
        "sport.climbing":       "Escalada",
        "sport.golf":           "Golf",
        "sport.stationaryBike": "Bicicleta estática",
        "sport.elliptical":     "Elíptica",
        "sport.treadmill":      "Cinta",
        "sport.stairStepper":   "Escaladora",
        "sport.yoga":           "Yoga",
        "sport.pilates":        "Pilates",
        "sport.dance":          "Baile",
        "sport.boxing":         "Boxeo",
        "sport.martialArts":    "Artes marciales",
        "sport.hiit":           "HIIT",
        "sport.rowing":         "Remo",
        "sport.swimming":       "Natación",
        "sport.openWaterSwim":  "Natación en aguas abiertas",
        "sport.surfing":        "Surf",
        "sport.diving":         "Buceo",
        "sport.paddleboard":    "Paddleboard",
        "sport.kayaking":       "Kayak",
        "sport.tennis":         "Tenis",
        "sport.soccer":         "Fútbol",
        "sport.basketball":     "Baloncesto",
        "sport.volleyball":     "Voleibol",
        "sport.baseball":       "Béisbol",
        "sport.padel":          "Pádel",

        // Sport detail / past-session UI
        "Your stats":               "Tus estadísticas",
        "sessions":                 "sesiones",
        "Total time":               "Tiempo total",
        "Avg Pace":                 "Ritmo medio",
        "History":                  "Historial",
        "No sessions yet":          "Aún no hay sesiones",
        "Tap Start to log your first session.": "Toca Inicio para registrar tu primera sesión.",
        "Start session":            "Iniciar sesión",

        // AI Route planner
        "route.title":        "Ruta IA",
        "route.subtitle":     "Deja que PowerPump te planee un circuito desde donde estás",
        "route.pickDistance": "Elige tu distancia",
        "route.generate":     "Generar mi ruta",
        "route.generating":   "Creando tu ruta…",
        "route.regenerate":   "Probar otra ruta",
        "route.runThis":      "Correr esta ruta",
        "route.custom":       "Personalizada",
        "route.failed":       "No se pudo crear una ruta aquí. Prueba una distancia más corta o muévete a una calle con caminos.",
        "route.plannedLabel": "Ruta planeada",
        "route.stageA":       "A",
        "route.stageB":       "B",
        "route.stageC":       "C",
        "route.km":           "km",
        "voice.route.start":  "Empezamos tu ruta. Sigue la línea azul. ¡Vamos!",
        "voice.route.stageB": "¡Buen ritmo! Llegaste a la etapa B, la mitad del recorrido. Sigue así.",
        "voice.route.stageC": "Etapa final. Ya casi llegas, ¡empuja hasta la meta!",
        "voice.route.finish": "Ruta completada. ¡Increíble trabajo!",
    ]

    // MARK: - French

    private static let fr: [String: String] = [
        "program.walk.name": "Marcher pour Maigrir",
        "program.walk.subtitle": "Programme de marche de 20 semaines à intensité progressive",
        "program.walk.phase1.title": "Adoptez une vie active",
        "program.walk.phase1.body": "Commencez votre parcours en marchant. Activez le corps et intégrez la marche à votre routine.",
        "program.walk.phase2.title": "Brûleur de calories",
        "program.walk.phase2.body": "Suivez un programme scientifique pour perdre du poids. Marchez plus longtemps et plus vite chaque semaine.",
        "program.walk.phase3.title": "Brûlez plus vite",
        "program.walk.phase3.body": "Brûlez la graisse efficacement, stimulez le métabolisme et créez l'effet \"afterburn\".",
        "program.walk.goal1": "Intégrez plus de marche à votre vie",
        "program.walk.goal2": "Sentez-vous plus heureux et actif",
        "program.walk.goal3": "Bâtissez une habitude durable",

        "program.run.name": "Courir pour maigrir",
        "program.run.subtitle": "Programme marche-trottinement-course sur 12 semaines",
        "program.run.phase1.title": "Mettez-vous en route",
        "program.run.phase1.body": "Construisez une base avec des intervalles marche-trottinement.",
        "program.run.phase2.title": "Intervalles brûleurs",
        "program.run.phase2.body": "Ajoutez des accélérations qui boostent le métabolisme.",
        "program.run.phase3.title": "Courez fort",
        "program.run.phase3.body": "Mélangez courses longues et sprints pour brûler un max.",
        "program.run.goal1": "Perdre du poids sans perdre la motivation",
        "program.run.goal2": "Courir 3 fois par semaine régulièrement",
        "program.run.goal3": "Améliorer votre santé cardiovasculaire",

        "program.pace.name": "Académie Running",
        "program.pace.subtitle": "8 semaines de tempo et fractionné",
        "program.pace.phase1.title": "Base tempo",
        "program.pace.phase1.body": "Apprenez à tenir une allure soutenue et améliorez votre efficacité cardio.",
        "program.pace.phase2.title": "Travail de vitesse",
        "program.pace.phase2.body": "Ajoutez du fractionné pour grimper en VO2 max.",
        "program.pace.phase3.title": "Prêt pour la course",
        "program.pace.phase3.body": "Affûtez-vous avec sprints courts pour baisser votre temps au km.",
        "program.pace.goal1": "Courir plus vite à toutes distances",
        "program.pace.goal2": "Capacité aérobie et anaérobie",
        "program.pace.goal3": "S'entraîner comme un vrai coureur",

        "program.5k.name": "Mon premier 5K",
        "program.5k.subtitle": "Plan canapé-5K en 12 semaines",
        "program.5k.phase1.title": "Base marche-course",
        "program.5k.phase1.body": "Alternez marches et petits trottinements pour adapter votre corps.",
        "program.5k.phase2.title": "Construire la course",
        "program.5k.phase2.body": "Étendez les trottinements jusqu'à courir 20+ min sans arrêt.",
        "program.5k.phase3.title": "Finir le 5K",
        "program.5k.phase3.body": "Consolidez les 30 min et terminez le 5K avec un sprint.",
        "program.5k.goal1": "Courir 5K sans arrêt en 12 semaines",
        "program.5k.goal2": "Bâtir une habitude solide",
        "program.5k.goal3": "Fier de finir votre première distance",

        "badge.lowImpact": "Impact faible",
        "badge.scienceBacked": "Efficacité prouvée",
        "badge.beginnerFriendly": "Pour débutants",
        "badge.gradualDuration": "Durée progressive",
        "badge.fatBurning": "Brûle-graisse",
        "badge.progressive": "Progressif",
        "badge.tempoTraining": "Tempo",
        "badge.intervalScience": "Science du fractionné",
        "badge.intermediate": "Intermédiaire",
        "badge.couchTo5k": "Du canapé au 5K",

        "voice.warmup": "échauffement",
        "voice.walk": "marche",
        "voice.briskWalk": "marche rapide",
        "voice.jog": "trottinement",
        "voice.run": "course",
        "voice.fastRun": "course rapide",
        "voice.sprint": "sprint",
        "voice.cooldown": "retour au calme",
        "voice.rest": "repos",
        "voice.start": "Commencez par",
        "voice.now": "Maintenant",
        "voice.halfway": "À la moitié. Continuez.",
        "voice.finish": "Séance terminée. Bravo !",
        "voice.paused": "Séance en pause.",
        "voice.resumed": "Reprise.",
        "voice.duration.minutes": "pendant %d minutes",
        "voice.duration.seconds": "pendant %d secondes",
        "voice.duration.minutesSeconds": "pendant %d minutes %d secondes",

        "Walk & Run Programs": "Programmes marche & course",
        "Lose weight · 5K · Pace · Voice coach": "Maigrir · 5K · Rythme · Coach vocal",
        "Pick a program and start today": "Choisissez un programme",
        "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.":
            "Des séances guidées par la voix qui adaptent marche, trottinement et course pour progresser sans risque.",
        "Introduction": "Introduction",
        "Progress": "Progrès",
        "About the programs": "À propos",
        "Expected results": "Résultats attendus",
        "Your personalised plan": "Votre plan personnalisé",
        "Scientific hybrid": "Hybride scientifique",
        "Walking · Jogging · Running": "Marche · Trottinement · Course",
        "Start Now": "Commencer",
        "Day": "Jour",
        "Day complete!": "Jour terminé !",
        "Save": "Enregistrer",
        "Discard": "Abandonner",
        "Finish session?": "Terminer la séance ?",
        "Save your progress for this day?": "Enregistrer vos progrès ?",
        "Endurance": "Endurance",
        "Speed": "Vitesse",
        "Next": "Suivant",
        "Start": "Démarrer",
        "Finish": "Terminer",
        "Total": "Total",
        "Completed": "Terminé",

        "%lld-week program": "Programme de %lld semaines",
        "%lld days/week": "%lld jours/semaine",
        "Week %lld · Day %lld": "Semaine %lld · Jour %lld",
        "Week %lld": "Semaine %lld",
        "Weeks %lld-%lld": "Semaines %lld-%lld",
        "You finished week %lld, day %lld.": "Vous avez terminé la semaine %lld, jour %lld.",

        "Voice Coach": "Coach vocal",
        "Vibration": "Vibration",
        "Voice & Vibration": "Voix et vibration",

        "Sports": "Sports",
        "Track any sport": "Suivez n'importe quel sport",
        "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.":
            "Choisissez un sport pour démarrer une séance. Les sports en plein air utilisent le GPS. Tout se synchronise avec Apple Santé.",
        "Outdoor": "Plein air",
        "Indoor": "Intérieur",
        "Water": "Eau",
        "Team & Racquet": "Équipe et raquette",
        "GPS": "GPS",
        "Distance": "Distance",
        "Burned": "Brûlées",
        "Time": "Temps",
        "Done": "Terminé",
        "Workout complete": "Séance terminée",
        "Save this session to your history and Apple Health?":
            "Enregistrer cette séance dans votre historique et Apple Santé ?",
        "Cancel": "Annuler",
        "Location is off": "Localisation désactivée",
        "Open Settings": "Ouvrir les Réglages",
        "Allow Location": "Autoriser la localisation",
        "Location access needed": "Accès à la position requis",
        "PowerPump uses your location to trace your route and measure distance.":
            "PowerPump utilise votre position pour tracer votre parcours et mesurer la distance.",

        "sport.cycling":        "Cyclisme",
        "sport.hiking":         "Randonnée",
        "sport.skating":        "Patinage",
        "sport.skiing":         "Ski",
        "sport.snowboarding":   "Snowboard",
        "sport.climbing":       "Escalade",
        "sport.golf":           "Golf",
        "sport.stationaryBike": "Vélo d'appartement",
        "sport.elliptical":     "Vélo elliptique",
        "sport.treadmill":      "Tapis de course",
        "sport.stairStepper":   "Stepper",
        "sport.yoga":           "Yoga",
        "sport.pilates":        "Pilates",
        "sport.dance":          "Danse",
        "sport.boxing":         "Boxe",
        "sport.martialArts":    "Arts martiaux",
        "sport.hiit":           "HIIT",
        "sport.rowing":         "Rameur",
        "sport.swimming":       "Natation",
        "sport.openWaterSwim":  "Natation en eau libre",
        "sport.surfing":        "Surf",
        "sport.diving":         "Plongée",
        "sport.paddleboard":    "Paddle",
        "sport.kayaking":       "Kayak",
        "sport.tennis":         "Tennis",
        "sport.soccer":         "Football",
        "sport.basketball":     "Basket-ball",
        "sport.volleyball":     "Volleyball",
        "sport.baseball":       "Baseball",
        "sport.padel":          "Padel",

        // Sport detail / past-session UI
        "Your stats":               "Vos statistiques",
        "sessions":                 "séances",
        "Total time":               "Temps total",
        "Avg Pace":                 "Allure moyenne",
        "History":                  "Historique",
        "No sessions yet":          "Aucune séance pour le moment",
        "Tap Start to log your first session.": "Appuyez sur Démarrer pour enregistrer votre première séance.",
        "Start session":            "Démarrer la séance",

        // AI Route planner
        "route.title":        "Itinéraire IA",
        "route.subtitle":     "Laissez PowerPump tracer une boucle depuis votre position",
        "route.pickDistance": "Choisissez votre distance",
        "route.generate":     "Générer mon itinéraire",
        "route.generating":   "Création de votre itinéraire…",
        "route.regenerate":   "Essayer un autre itinéraire",
        "route.runThis":      "Suivre cet itinéraire",
        "route.custom":       "Personnalisé",
        "route.failed":       "Impossible de créer un itinéraire ici. Essayez une distance plus courte ou déplacez-vous vers une rue avec des chemins.",
        "route.plannedLabel": "Itinéraire prévu",
        "route.stageA":       "A",
        "route.stageB":       "B",
        "route.stageC":       "C",
        "route.km":           "km",
        "voice.route.start":  "On démarre votre itinéraire. Suivez la ligne bleue. C'est parti !",
        "voice.route.stageB": "Bon rythme ! Vous avez atteint l'étape B, la moitié du parcours. Continuez.",
        "voice.route.stageC": "Dernière étape. Vous y êtes presque, foncez jusqu'à l'arrivée !",
        "voice.route.finish": "Itinéraire terminé. Superbe travail !",
    ]

    // MARK: - Italian

    private static let it: [String: String] = [
        "program.walk.name": "Camminare per Dimagrire",
        "program.walk.subtitle": "Programma di 20 settimane di camminata progressiva",
        "program.walk.phase1.title": "Adattati a una vita attiva",
        "program.walk.phase1.body": "Inizia il tuo percorso camminando. Attiva il corpo con camminate nella tua routine.",
        "program.walk.phase2.title": "Bruciatore di calorie",
        "program.walk.phase2.body": "Segui un programma scientifico per dimagrire. Cammina più a lungo e più veloce.",
        "program.walk.phase3.title": "Brucia più veloce",
        "program.walk.phase3.body": "Brucia grasso più efficacemente, attiva il metabolismo e crea l'afterburn.",
        "program.walk.goal1": "Incorpora più camminate nel tuo stile di vita",
        "program.walk.goal2": "Senti più felice e attivo",
        "program.walk.goal3": "Crea un'abitudine quotidiana",

        "program.run.name": "Correre per dimagrire",
        "program.run.subtitle": "Programma cammina-trotta-corri di 12 settimane",
        "program.run.phase1.title": "Mettiti in moto",
        "program.run.phase1.body": "Crea una base con intervalli cammina-trotta.",
        "program.run.phase2.title": "Intervalli brucia-grasso",
        "program.run.phase2.body": "Aggiungi tratti di corsa che alzano il metabolismo.",
        "program.run.phase3.title": "Corri forte",
        "program.run.phase3.body": "Mescola corse lunghe e sprint per massimo consumo calorico.",
        "program.run.goal1": "Perdere peso senza perdere la motivazione",
        "program.run.goal2": "Creare l'abitudine di correre 3 volte/settimana",
        "program.run.goal3": "Migliorare la salute cardiovascolare",

        "program.pace.name": "Accademia Running",
        "program.pace.subtitle": "8 settimane di tempo run e fartlek",
        "program.pace.phase1.title": "Base di tempo",
        "program.pace.phase1.body": "Impara a mantenere un'andatura comoda-forte.",
        "program.pace.phase2.title": "Lavoro di velocità",
        "program.pace.phase2.body": "Aggiungi intervalli per alzare il VO2 max.",
        "program.pace.phase3.title": "Pronto per la gara",
        "program.pace.phase3.body": "Affila con sprint per abbassare il tempo al km.",
        "program.pace.goal1": "Correre più veloce a ogni distanza",
        "program.pace.goal2": "Capacità aerobica e anaerobica",
        "program.pace.goal3": "Allenarti come un vero runner",

        "program.5k.name": "Il mio primo 5K",
        "program.5k.subtitle": "Piano dal divano al 5K in 12 settimane",
        "program.5k.phase1.title": "Base cammina-corri",
        "program.5k.phase1.body": "Alterna camminate e trotti corti per adattare il corpo.",
        "program.5k.phase2.title": "Costruire la corsa",
        "program.5k.phase2.body": "Estendi i trotti fino a correre 20+ min senza fermarti.",
        "program.5k.phase3.title": "Finire il 5K",
        "program.5k.phase3.body": "Consolida i 30 minuti e finisci il primo 5K con uno sprint.",
        "program.5k.goal1": "Correre 5K senza sosta in 12 settimane",
        "program.5k.goal2": "Sviluppare una solida abitudine di corsa",
        "program.5k.goal3": "Orgoglio di finire la tua prima distanza",

        "badge.lowImpact": "Basso impatto",
        "badge.scienceBacked": "Efficacia provata",
        "badge.beginnerFriendly": "Adatto ai principianti",
        "badge.gradualDuration": "Durata graduale",
        "badge.fatBurning": "Brucia grassi",
        "badge.progressive": "Progressivo",
        "badge.tempoTraining": "Allenamento tempo",
        "badge.intervalScience": "Scienza degli intervalli",
        "badge.intermediate": "Intermedio",
        "badge.couchTo5k": "Dal divano al 5K",

        "voice.warmup": "riscaldamento",
        "voice.walk": "cammina",
        "voice.briskWalk": "cammina veloce",
        "voice.jog": "trotta",
        "voice.run": "corri",
        "voice.fastRun": "corri veloce",
        "voice.sprint": "sprint",
        "voice.cooldown": "defaticamento",
        "voice.rest": "riposo",
        "voice.start": "Inizia con",
        "voice.now": "Ora",
        "voice.halfway": "Metà intervallo. Continua.",
        "voice.finish": "Sessione completa. Bravo!",
        "voice.paused": "Sessione in pausa.",
        "voice.resumed": "Riprendiamo.",
        "voice.duration.minutes": "per %d minuti",
        "voice.duration.seconds": "per %d secondi",
        "voice.duration.minutesSeconds": "per %d minuti %d secondi",

        "Walk & Run Programs": "Programmi camminata e corsa",
        "Lose weight · 5K · Pace · Voice coach": "Dimagrire · 5K · Ritmo · Coach vocale",
        "Pick a program and start today": "Scegli un programma e inizia oggi",
        "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.":
            "Sessioni guidate dalla voce che adattano camminate, trottini e corse nel tempo.",
        "Introduction": "Introduzione",
        "Progress": "Progresso",
        "About the programs": "Sui programmi",
        "Expected results": "Risultati attesi",
        "Your personalised plan": "Il tuo piano personalizzato",
        "Scientific hybrid": "Ibrido scientifico",
        "Walking · Jogging · Running": "Camminare · Trottare · Correre",
        "Start Now": "Inizia ora",
        "Day": "Giorno",
        "Day complete!": "Giorno completato!",
        "Save": "Salva",
        "Discard": "Annulla",
        "Finish session?": "Terminare la sessione?",
        "Save your progress for this day?": "Salvare i progressi?",
        "Endurance": "Resistenza",
        "Speed": "Velocità",
        "Next": "Prossimo",
        "Start": "Inizio",
        "Finish": "Termina",
        "Total": "Totale",
        "Completed": "Completato",

        "%lld-week program": "Programma di %lld settimane",
        "%lld days/week": "%lld giorni/settimana",
        "Week %lld · Day %lld": "Settimana %lld · Giorno %lld",
        "Week %lld": "Settimana %lld",
        "Weeks %lld-%lld": "Settimane %lld-%lld",
        "You finished week %lld, day %lld.": "Hai finito la settimana %lld, giorno %lld.",

        "Voice Coach": "Coach vocale",
        "Vibration": "Vibrazione",
        "Voice & Vibration": "Voce e vibrazione",

        "Sports": "Sport",
        "Track any sport": "Traccia qualsiasi sport",
        "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.":
            "Scegli uno sport per iniziare una sessione. Gli sport all'aperto usano il GPS. Tutto si sincronizza con Apple Salute.",
        "Outdoor": "All'aperto",
        "Indoor": "Al chiuso",
        "Water": "Acqua",
        "Team & Racquet": "Squadra e racchetta",
        "GPS": "GPS",
        "Distance": "Distanza",
        "Burned": "Bruciate",
        "Time": "Tempo",
        "Done": "Fatto",
        "Workout complete": "Sessione completata",
        "Save this session to your history and Apple Health?":
            "Salvare questa sessione nella cronologia e in Apple Salute?",
        "Cancel": "Annulla",
        "Location is off": "Posizione disattivata",
        "Open Settings": "Apri Impostazioni",
        "Allow Location": "Consenti posizione",
        "Location access needed": "Serve l'accesso alla posizione",
        "PowerPump uses your location to trace your route and measure distance.":
            "PowerPump usa la tua posizione per tracciare il percorso e misurare la distanza.",

        "sport.cycling":        "Ciclismo",
        "sport.hiking":         "Escursionismo",
        "sport.skating":        "Pattinaggio",
        "sport.skiing":         "Sci",
        "sport.snowboarding":   "Snowboard",
        "sport.climbing":       "Arrampicata",
        "sport.golf":           "Golf",
        "sport.stationaryBike": "Cyclette",
        "sport.elliptical":     "Ellittica",
        "sport.treadmill":      "Tapis roulant",
        "sport.stairStepper":   "Stepper",
        "sport.yoga":           "Yoga",
        "sport.pilates":        "Pilates",
        "sport.dance":          "Danza",
        "sport.boxing":         "Boxe",
        "sport.martialArts":    "Arti marziali",
        "sport.hiit":           "HIIT",
        "sport.rowing":         "Vogatore",
        "sport.swimming":       "Nuoto",
        "sport.openWaterSwim":  "Nuoto in acque libere",
        "sport.surfing":        "Surf",
        "sport.diving":         "Subacquea",
        "sport.paddleboard":    "Paddleboard",
        "sport.kayaking":       "Kayak",
        "sport.tennis":         "Tennis",
        "sport.soccer":         "Calcio",
        "sport.basketball":     "Basket",
        "sport.volleyball":     "Pallavolo",
        "sport.baseball":       "Baseball",
        "sport.padel":          "Padel",

        // Sport detail / past-session UI
        "Your stats":               "Le tue statistiche",
        "sessions":                 "sessioni",
        "Total time":               "Tempo totale",
        "Avg Pace":                 "Ritmo medio",
        "History":                  "Cronologia",
        "No sessions yet":          "Ancora nessuna sessione",
        "Tap Start to log your first session.": "Tocca Inizia per registrare la tua prima sessione.",
        "Start session":            "Inizia sessione",

        // AI Route planner
        "route.title":        "Percorso IA",
        "route.subtitle":     "Lascia che PowerPump ti crei un anello da dove sei",
        "route.pickDistance": "Scegli la distanza",
        "route.generate":     "Genera il mio percorso",
        "route.generating":   "Sto creando il percorso…",
        "route.regenerate":   "Prova un altro percorso",
        "route.runThis":      "Corri questo percorso",
        "route.custom":       "Personalizzata",
        "route.failed":       "Impossibile creare un percorso qui. Prova una distanza più breve o spostati su una strada con sentieri.",
        "route.plannedLabel": "Percorso pianificato",
        "route.stageA":       "A",
        "route.stageB":       "B",
        "route.stageC":       "C",
        "route.km":           "km",
        "voice.route.start":  "Iniziamo il tuo percorso. Segui la linea blu. Andiamo!",
        "voice.route.stageB": "Ottimo ritmo! Hai raggiunto la tappa B, a metà percorso. Continua così.",
        "voice.route.stageC": "Tappa finale. Ci sei quasi, spingi fino al traguardo!",
        "voice.route.finish": "Percorso completato. Ottimo lavoro!",
    ]

    // MARK: - Portuguese (Brazil)

    private static let ptBR: [String: String] = [
        "program.walk.name": "Caminhar para Emagrecer",
        "program.walk.subtitle": "Programa de 20 semanas com intensidade progressiva",
        "program.walk.phase1.title": "Adapte-se a uma vida ativa",
        "program.walk.phase1.body": "Comece sua jornada caminhando. Ative o corpo com caminhadas na rotina.",
        "program.walk.phase2.title": "Queimador de calorias",
        "program.walk.phase2.body": "Siga um programa científico para emagrecer. Caminhe mais e mais rápido a cada semana.",
        "program.walk.phase3.title": "Queime mais rápido",
        "program.walk.phase3.body": "Queime gordura com mais eficácia, acelere o metabolismo e crie o efeito afterburn.",
        "program.walk.goal1": "Inclua mais caminhadas no seu estilo de vida",
        "program.walk.goal2": "Sinta-se mais feliz e ativo",
        "program.walk.goal3": "Crie um hábito diário duradouro",

        "program.run.name": "Correr para emagrecer",
        "program.run.subtitle": "Programa caminhar-trotar-correr de 12 semanas",
        "program.run.phase1.title": "Coloque o corpo em movimento",
        "program.run.phase1.body": "Crie uma base com intervalos caminhar-trotar.",
        "program.run.phase2.title": "Intervalos queimadores",
        "program.run.phase2.body": "Adicione trechos de corrida que elevam o metabolismo.",
        "program.run.phase3.title": "Corra forte",
        "program.run.phase3.body": "Combine corridas longas e sprints para máximo gasto.",
        "program.run.goal1": "Perder peso sem perder motivação",
        "program.run.goal2": "Criar o hábito de correr 3x/semana",
        "program.run.goal3": "Melhorar sua saúde cardiovascular",

        "program.pace.name": "Academia Running",
        "program.pace.subtitle": "8 semanas de tempo e intervalos",
        "program.pace.phase1.title": "Base de tempo",
        "program.pace.phase1.body": "Aprenda a manter um ritmo confortável-forte.",
        "program.pace.phase2.title": "Trabalho de velocidade",
        "program.pace.phase2.body": "Adicione intervalos para subir o VO2 max.",
        "program.pace.phase3.title": "Pronto pra prova",
        "program.pace.phase3.body": "Afie com sprints curtos para baixar seu tempo por km.",
        "program.pace.goal1": "Correr mais rápido em qualquer distância",
        "program.pace.goal2": "Capacidade aeróbica e anaeróbica",
        "program.pace.goal3": "Treinar como um corredor de verdade",

        "program.5k.name": "Meu primeiro 5K",
        "program.5k.subtitle": "Plano do sofá ao 5K em 12 semanas",
        "program.5k.phase1.title": "Base caminhar-correr",
        "program.5k.phase1.body": "Alterne caminhadas e trotes curtos para adaptar o corpo.",
        "program.5k.phase2.title": "Construir a corrida",
        "program.5k.phase2.body": "Aumente os trotes até correr 20+ min sem parar.",
        "program.5k.phase3.title": "Terminar o 5K",
        "program.5k.phase3.body": "Consolide os 30 min e termine o primeiro 5K com um sprint.",
        "program.5k.goal1": "Correr 5K sem parar em 12 semanas",
        "program.5k.goal2": "Desenvolver um hábito sólido de corrida",
        "program.5k.goal3": "Sentir orgulho de terminar sua primeira distância",

        "badge.lowImpact": "Baixo impacto",
        "badge.scienceBacked": "Eficácia comprovada",
        "badge.beginnerFriendly": "Para iniciantes",
        "badge.gradualDuration": "Duração gradual",
        "badge.fatBurning": "Queima gordura",
        "badge.progressive": "Progressivo",
        "badge.tempoTraining": "Treino tempo",
        "badge.intervalScience": "Ciência do intervalo",
        "badge.intermediate": "Intermediário",
        "badge.couchTo5k": "Do sofá ao 5K",

        "voice.warmup": "aquecimento",
        "voice.walk": "caminhe",
        "voice.briskWalk": "caminhe rápido",
        "voice.jog": "trote",
        "voice.run": "corra",
        "voice.fastRun": "corra rápido",
        "voice.sprint": "sprint",
        "voice.cooldown": "desaqueça",
        "voice.rest": "descanse",
        "voice.start": "Comece com",
        "voice.now": "Agora",
        "voice.halfway": "Metade do intervalo. Continue.",
        "voice.finish": "Sessão completa. Muito bem!",
        "voice.paused": "Sessão pausada.",
        "voice.resumed": "Retomando.",
        "voice.duration.minutes": "por %d minutos",
        "voice.duration.seconds": "por %d segundos",
        "voice.duration.minutesSeconds": "por %d minutos %d segundos",

        "Walk & Run Programs": "Programas de caminhada e corrida",
        "Lose weight · 5K · Pace · Voice coach": "Emagrecer · 5K · Ritmo · Voz coach",
        "Pick a program and start today": "Escolha um programa e comece hoje",
        "Voice-guided sessions adapt walks, jogs, and runs over weeks so you build up safely.":
            "Sessões guiadas por voz que adaptam caminhadas, trotes e corridas ao longo das semanas.",
        "Introduction": "Introdução",
        "Progress": "Progresso",
        "About the programs": "Sobre os programas",
        "Expected results": "Resultados esperados",
        "Your personalised plan": "Seu plano personalizado",
        "Scientific hybrid": "Híbrido científico",
        "Walking · Jogging · Running": "Caminhar · Trotar · Correr",
        "Start Now": "Começar agora",
        "Day": "Dia",
        "Day complete!": "Dia concluído!",
        "Save": "Salvar",
        "Discard": "Descartar",
        "Finish session?": "Terminar a sessão?",
        "Save your progress for this day?": "Salvar seu progresso?",
        "Endurance": "Resistência",
        "Speed": "Velocidade",
        "Next": "Próximo",
        "Start": "Início",
        "Finish": "Terminar",
        "Total": "Total",
        "Completed": "Concluído",

        "%lld-week program": "Programa de %lld semanas",
        "%lld days/week": "%lld dias/semana",
        "Week %lld · Day %lld": "Semana %lld · Dia %lld",
        "Week %lld": "Semana %lld",
        "Weeks %lld-%lld": "Semanas %lld-%lld",
        "You finished week %lld, day %lld.": "Você terminou a semana %lld, dia %lld.",

        "Voice Coach": "Coach de voz",
        "Vibration": "Vibração",
        "Voice & Vibration": "Voz e vibração",

        "Sports": "Esportes",
        "Track any sport": "Acompanhe qualquer esporte",
        "Pick a sport to start a tracked session. Outdoor sports use GPS; results sync to Apple Health.":
            "Escolha um esporte para iniciar uma sessão. Esportes ao ar livre usam GPS. Tudo é sincronizado com Apple Saúde.",
        "Outdoor": "Ar livre",
        "Indoor": "Interno",
        "Water": "Água",
        "Team & Racquet": "Time e raquete",
        "GPS": "GPS",
        "Distance": "Distância",
        "Burned": "Queimadas",
        "Time": "Tempo",
        "Done": "Pronto",
        "Workout complete": "Sessão concluída",
        "Save this session to your history and Apple Health?":
            "Salvar esta sessão no histórico e no Apple Saúde?",
        "Cancel": "Cancelar",
        "Location is off": "Localização desativada",
        "Open Settings": "Abrir Ajustes",
        "Allow Location": "Permitir localização",
        "Location access needed": "Precisa de acesso à localização",
        "PowerPump uses your location to trace your route and measure distance.":
            "PowerPump usa sua localização para traçar sua rota e medir distância.",

        "sport.cycling":        "Ciclismo",
        "sport.hiking":         "Trilha",
        "sport.skating":        "Patinação",
        "sport.skiing":         "Esqui",
        "sport.snowboarding":   "Snowboard",
        "sport.climbing":       "Escalada",
        "sport.golf":           "Golfe",
        "sport.stationaryBike": "Bike ergométrica",
        "sport.elliptical":     "Elíptico",
        "sport.treadmill":      "Esteira",
        "sport.stairStepper":   "Stepper",
        "sport.yoga":           "Yoga",
        "sport.pilates":        "Pilates",
        "sport.dance":          "Dança",
        "sport.boxing":         "Boxe",
        "sport.martialArts":    "Artes marciais",
        "sport.hiit":           "HIIT",
        "sport.rowing":         "Remo",
        "sport.swimming":       "Natação",
        "sport.openWaterSwim":  "Natação em águas abertas",
        "sport.surfing":        "Surfe",
        "sport.diving":         "Mergulho",
        "sport.paddleboard":    "Stand-up paddle",
        "sport.kayaking":       "Caiaque",
        "sport.tennis":         "Tênis",
        "sport.soccer":         "Futebol",
        "sport.basketball":     "Basquete",
        "sport.volleyball":     "Vôlei",
        "sport.baseball":       "Beisebol",
        "sport.padel":          "Padel",

        // Sport detail / past-session UI
        "Your stats":               "Suas estatísticas",
        "sessions":                 "sessões",
        "Total time":               "Tempo total",
        "Avg Pace":                 "Ritmo médio",
        "History":                  "Histórico",
        "No sessions yet":          "Ainda sem sessões",
        "Tap Start to log your first session.": "Toque em Iniciar para registrar sua primeira sessão.",
        "Start session":            "Iniciar sessão",

        // AI Route planner
        "route.title":        "Rota IA",
        "route.subtitle":     "Deixe o PowerPump planejar um circuito de onde você está",
        "route.pickDistance": "Escolha sua distância",
        "route.generate":     "Gerar minha rota",
        "route.generating":   "Criando sua rota…",
        "route.regenerate":   "Tentar outra rota",
        "route.runThis":      "Correr esta rota",
        "route.custom":       "Personalizada",
        "route.failed":       "Não foi possível criar uma rota aqui. Tente uma distância menor ou vá para uma rua com caminhos.",
        "route.plannedLabel": "Rota planejada",
        "route.stageA":       "A",
        "route.stageB":       "B",
        "route.stageC":       "C",
        "route.km":           "km",
        "voice.route.start":  "Vamos começar sua rota. Siga a linha azul. Bora!",
        "voice.route.stageB": "Bom ritmo! Você chegou à etapa B, na metade do percurso. Continue assim.",
        "voice.route.stageC": "Etapa final. Você está quase lá, vá até o fim!",
        "voice.route.finish": "Rota concluída. Trabalho incrível!",
    ]
}

/// Shorthand for ProgramStrings lookup. Used in voice + UI code.
func PT(_ key: String) -> String { ProgramStrings.value(key) }
