import Foundation

struct RecipeDatabase {
    static let all: [Recipe] = muscleGain + weightLoss + maintenance + plantBased

    // MARK: - Muscle Gain

    static let muscleGain: [Recipe] = [
        Recipe(
            id: "chicken_rice_bowl",
            name: "Chicken & Rice Bowl",
            goal: .muscleGain,
            emoji: "🍚",
            prepMinutes: 25,
            servings: 1,
            tags: ["High Protein", "Classic", "Meal Prep"],
            ingredients: [
                Ingredient(amount: "200g", name: "Chicken breast"),
                Ingredient(amount: "150g", name: "White rice (cooked)"),
                Ingredient(amount: "1 cup", name: "Broccoli"),
                Ingredient(amount: "1 tbsp", name: "Olive oil"),
                Ingredient(amount: "to taste", name: "Salt, pepper, garlic powder"),
            ],
            steps: [
                "Season chicken breast with salt, pepper, and garlic powder.",
                "Heat olive oil in a pan over medium-high heat.",
                "Cook chicken 6-7 min per side until golden and cooked through. Rest 2 min, then slice.",
                "Steam or microwave broccoli for 3 minutes.",
                "Serve sliced chicken over rice with broccoli on the side.",
            ],
            nutrition: NutritionInfo(calories: 620, protein: 55, carbs: 65, fat: 12)
        ),
        Recipe(
            id: "egg_white_omelette",
            name: "Egg White Omelette",
            goal: .muscleGain,
            emoji: "🍳",
            prepMinutes: 10,
            servings: 1,
            tags: ["High Protein", "Quick", "Low Fat"],
            ingredients: [
                Ingredient(amount: "6 large", name: "Egg whites"),
                Ingredient(amount: "1/2 cup", name: "Spinach"),
                Ingredient(amount: "1/4 cup", name: "Bell pepper, diced"),
                Ingredient(amount: "30g", name: "Mozzarella"),
                Ingredient(amount: "1 tsp", name: "Olive oil"),
            ],
            steps: [
                "Beat egg whites with a pinch of salt until slightly frothy.",
                "Heat oil in a non-stick pan over medium heat.",
                "Pour in egg whites and let set for 1-2 minutes.",
                "Add spinach, pepper, and mozzarella to one half.",
                "Fold over and cook 1 more minute. Serve immediately.",
            ],
            nutrition: NutritionInfo(calories: 220, protein: 32, carbs: 5, fat: 8)
        ),
        Recipe(
            id: "tuna_pasta",
            name: "Tuna Pasta",
            goal: .muscleGain,
            emoji: "🍝",
            prepMinutes: 20,
            servings: 2,
            tags: ["High Protein", "Budget", "Meal Prep"],
            ingredients: [
                Ingredient(amount: "200g", name: "Whole wheat pasta"),
                Ingredient(amount: "2 cans (160g each)", name: "Tuna in water, drained"),
                Ingredient(amount: "1 cup", name: "Cherry tomatoes, halved"),
                Ingredient(amount: "2 tbsp", name: "Olive oil"),
                Ingredient(amount: "2 cloves", name: "Garlic, minced"),
                Ingredient(amount: "to taste", name: "Salt, pepper, chili flakes"),
            ],
            steps: [
                "Cook pasta according to package instructions. Reserve ¼ cup pasta water.",
                "In a pan, sauté garlic in olive oil for 1 minute over medium heat.",
                "Add cherry tomatoes and cook 3-4 minutes until softened.",
                "Add tuna and stir gently to combine.",
                "Toss with drained pasta, adding pasta water if needed. Season and serve.",
            ],
            nutrition: NutritionInfo(calories: 540, protein: 48, carbs: 62, fat: 10)
        ),
        Recipe(
            id: "greek_yogurt_bowl",
            name: "Greek Yogurt Protein Bowl",
            goal: .muscleGain,
            emoji: "🥣",
            prepMinutes: 5,
            servings: 1,
            tags: ["High Protein", "No Cook", "Breakfast"],
            ingredients: [
                Ingredient(amount: "250g", name: "Greek yogurt (0%)"),
                Ingredient(amount: "1 scoop (30g)", name: "Whey protein (vanilla)"),
                Ingredient(amount: "50g", name: "Oats"),
                Ingredient(amount: "1 medium", name: "Banana, sliced"),
                Ingredient(amount: "1 tbsp", name: "Peanut butter"),
                Ingredient(amount: "1 tsp", name: "Honey"),
            ],
            steps: [
                "Mix Greek yogurt with whey protein until smooth.",
                "Stir in oats.",
                "Top with banana slices and a drizzle of peanut butter.",
                "Finish with honey. Serve immediately or refrigerate overnight.",
            ],
            nutrition: NutritionInfo(calories: 580, protein: 52, carbs: 68, fat: 10)
        ),
        Recipe(
            id: "beef_bowl",
            name: "Lean Beef & Sweet Potato Bowl",
            goal: .muscleGain,
            emoji: "🥩",
            prepMinutes: 30,
            servings: 2,
            tags: ["High Protein", "Iron Rich", "Meal Prep"],
            ingredients: [
                Ingredient(amount: "300g", name: "Lean ground beef (90%)"),
                Ingredient(amount: "2 medium", name: "Sweet potatoes"),
                Ingredient(amount: "1 cup", name: "Mixed greens"),
                Ingredient(amount: "1 tbsp", name: "Olive oil"),
                Ingredient(amount: "1 tsp each", name: "Cumin, paprika, garlic powder"),
            ],
            steps: [
                "Pierce sweet potatoes and microwave 8-10 min until tender. Slice open.",
                "Brown ground beef in a pan over medium-high heat, breaking it apart.",
                "Season with cumin, paprika, and garlic powder. Cook until no pink remains.",
                "Serve beef over sweet potato halves with mixed greens on the side.",
            ],
            nutrition: NutritionInfo(calories: 590, protein: 46, carbs: 42, fat: 22)
        ),
        Recipe(
            id: "protein_pancakes",
            name: "Protein Pancakes",
            goal: .muscleGain,
            emoji: "🥞",
            prepMinutes: 15,
            servings: 1,
            tags: ["High Protein", "Breakfast", "Quick"],
            ingredients: [
                Ingredient(amount: "1 scoop (30g)", name: "Whey protein"),
                Ingredient(amount: "50g", name: "Oats"),
                Ingredient(amount: "2 whole", name: "Eggs"),
                Ingredient(amount: "1/2 medium", name: "Banana"),
                Ingredient(amount: "1/2 tsp", name: "Baking powder"),
                Ingredient(amount: "splash", name: "Milk"),
            ],
            steps: [
                "Blend oats into flour. Mash banana.",
                "Mix all ingredients until a smooth batter forms. Add milk if too thick.",
                "Heat a non-stick pan over medium heat with a little cooking spray.",
                "Pour small circles of batter. Cook 2-3 min per side until golden.",
                "Serve with berries or a drizzle of honey.",
            ],
            nutrition: NutritionInfo(calories: 480, protein: 42, carbs: 48, fat: 12)
        ),
    ]

    // MARK: - Weight Loss

    static let weightLoss: [Recipe] = [
        Recipe(
            id: "grilled_chicken_salad",
            name: "Grilled Chicken Salad",
            goal: .weightLoss,
            emoji: "🥗",
            prepMinutes: 15,
            servings: 1,
            tags: ["Low Calorie", "High Protein", "Quick"],
            ingredients: [
                Ingredient(amount: "150g", name: "Chicken breast"),
                Ingredient(amount: "2 cups", name: "Mixed greens"),
                Ingredient(amount: "1/2 cup", name: "Cherry tomatoes"),
                Ingredient(amount: "1/4", name: "Cucumber, sliced"),
                Ingredient(amount: "1 tbsp", name: "Olive oil + lemon juice"),
                Ingredient(amount: "to taste", name: "Salt, pepper, oregano"),
            ],
            steps: [
                "Season chicken and grill or pan-sear 6 min per side. Let rest, then slice.",
                "Arrange greens, tomatoes, and cucumber in a bowl.",
                "Top with sliced chicken.",
                "Drizzle with olive oil and lemon juice. Season and toss.",
            ],
            nutrition: NutritionInfo(calories: 310, protein: 38, carbs: 10, fat: 12)
        ),
        Recipe(
            id: "tuna_salad_wrap",
            name: "Tuna Salad Lettuce Wraps",
            goal: .weightLoss,
            emoji: "🥬",
            prepMinutes: 8,
            servings: 1,
            tags: ["Low Carb", "No Cook", "Quick"],
            ingredients: [
                Ingredient(amount: "1 can (160g)", name: "Tuna in water, drained"),
                Ingredient(amount: "2 tbsp", name: "Greek yogurt (instead of mayo)"),
                Ingredient(amount: "1 stalk", name: "Celery, diced"),
                Ingredient(amount: "1 tbsp", name: "Dijon mustard"),
                Ingredient(amount: "4 large", name: "Romaine lettuce leaves"),
                Ingredient(amount: "to taste", name: "Salt, pepper, lemon juice"),
            ],
            steps: [
                "Mix tuna, Greek yogurt, celery, mustard, and lemon juice in a bowl.",
                "Season with salt and pepper.",
                "Spoon mixture into lettuce leaves.",
                "Fold and eat like a taco.",
            ],
            nutrition: NutritionInfo(calories: 220, protein: 35, carbs: 6, fat: 4)
        ),
        Recipe(
            id: "veggie_omelette",
            name: "Veggie Omelette",
            goal: .weightLoss,
            emoji: "🫑",
            prepMinutes: 12,
            servings: 1,
            tags: ["Low Calorie", "Vegetarian", "Quick"],
            ingredients: [
                Ingredient(amount: "3 whole", name: "Eggs"),
                Ingredient(amount: "1/2 cup", name: "Spinach"),
                Ingredient(amount: "1/4 cup", name: "Mushrooms, sliced"),
                Ingredient(amount: "1/4 cup", name: "Tomato, diced"),
                Ingredient(amount: "1 tsp", name: "Olive oil"),
                Ingredient(amount: "to taste", name: "Salt, pepper, herbs"),
            ],
            steps: [
                "Sauté mushrooms and tomato in olive oil over medium heat for 3 min.",
                "Add spinach and cook until wilted.",
                "Beat eggs with salt and pepper. Pour over vegetables.",
                "Let set on the bottom, then fold over. Cook 1 more minute.",
            ],
            nutrition: NutritionInfo(calories: 280, protein: 22, carbs: 6, fat: 18)
        ),
        Recipe(
            id: "salmon_zucchini",
            name: "Salmon & Zucchini Noodles",
            goal: .weightLoss,
            emoji: "🐟",
            prepMinutes: 20,
            servings: 1,
            tags: ["Low Carb", "Omega-3", "Gourmet"],
            ingredients: [
                Ingredient(amount: "150g", name: "Salmon fillet"),
                Ingredient(amount: "2 medium", name: "Zucchini (spiralized or sliced thin)"),
                Ingredient(amount: "2 cloves", name: "Garlic, minced"),
                Ingredient(amount: "1 tbsp", name: "Olive oil"),
                Ingredient(amount: "1/2", name: "Lemon (juice + zest)"),
                Ingredient(amount: "to taste", name: "Salt, pepper, dill"),
            ],
            steps: [
                "Season salmon with salt, pepper, and lemon zest.",
                "Sear salmon in olive oil 4 min per side. Remove and flake.",
                "In the same pan, sauté garlic 30 seconds. Add zucchini noodles.",
                "Cook zucchini 2-3 min. Add lemon juice and dill.",
                "Plate zucchini, top with flaked salmon.",
            ],
            nutrition: NutritionInfo(calories: 350, protein: 34, carbs: 10, fat: 18)
        ),
        Recipe(
            id: "turkey_soup",
            name: "Turkey & Vegetable Soup",
            goal: .weightLoss,
            emoji: "🍲",
            prepMinutes: 35,
            servings: 3,
            tags: ["Low Calorie", "Meal Prep", "Filling"],
            ingredients: [
                Ingredient(amount: "300g", name: "Turkey breast, diced"),
                Ingredient(amount: "2 cups", name: "Broccoli florets"),
                Ingredient(amount: "2 medium", name: "Carrots, sliced"),
                Ingredient(amount: "1 stalk", name: "Celery, chopped"),
                Ingredient(amount: "1L", name: "Chicken broth (low sodium)"),
                Ingredient(amount: "1 tsp each", name: "Thyme, garlic powder, onion powder"),
            ],
            steps: [
                "Bring broth to a boil in a large pot.",
                "Add turkey, carrots, and celery. Simmer 15 minutes.",
                "Add broccoli and season with thyme, garlic, and onion powder.",
                "Simmer 10 more minutes until vegetables are tender.",
                "Adjust seasoning and serve hot.",
            ],
            nutrition: NutritionInfo(calories: 260, protein: 36, carbs: 14, fat: 4)
        ),
    ]

    // MARK: - Maintenance

    static let maintenance: [Recipe] = [
        Recipe(
            id: "overnight_oats",
            name: "Overnight Oats",
            goal: .maintenance,
            emoji: "🌙",
            prepMinutes: 5,
            servings: 1,
            tags: ["Meal Prep", "Breakfast", "No Cook"],
            ingredients: [
                Ingredient(amount: "80g", name: "Oats"),
                Ingredient(amount: "200ml", name: "Milk (or plant milk)"),
                Ingredient(amount: "100g", name: "Greek yogurt"),
                Ingredient(amount: "1 tbsp", name: "Chia seeds"),
                Ingredient(amount: "1 tbsp", name: "Honey"),
                Ingredient(amount: "1/2 cup", name: "Mixed berries"),
            ],
            steps: [
                "Combine oats, milk, Greek yogurt, chia seeds, and honey in a jar.",
                "Stir well. Cover and refrigerate overnight (at least 6 hours).",
                "In the morning, top with mixed berries.",
                "Enjoy cold straight from the jar.",
            ],
            nutrition: NutritionInfo(calories: 450, protein: 20, carbs: 70, fat: 8)
        ),
        Recipe(
            id: "sweet_potato_salmon",
            name: "Sweet Potato & Salmon",
            goal: .maintenance,
            emoji: "🍠",
            prepMinutes: 35,
            servings: 2,
            tags: ["Balanced", "Omega-3", "Meal Prep"],
            ingredients: [
                Ingredient(amount: "2 fillets (150g each)", name: "Salmon"),
                Ingredient(amount: "2 large", name: "Sweet potatoes"),
                Ingredient(amount: "1 cup", name: "Broccoli"),
                Ingredient(amount: "2 tbsp", name: "Olive oil"),
                Ingredient(amount: "1 tsp each", name: "Paprika, garlic powder"),
                Ingredient(amount: "to taste", name: "Salt, pepper, lemon"),
            ],
            steps: [
                "Preheat oven to 200°C. Cube sweet potatoes, toss with 1 tbsp oil and paprika.",
                "Roast sweet potatoes 25-30 min, flipping halfway.",
                "Season salmon with garlic, salt, and pepper. Pan-sear 4 min per side.",
                "Steam broccoli 4 minutes.",
                "Plate with a squeeze of lemon over the salmon.",
            ],
            nutrition: NutritionInfo(calories: 520, protein: 38, carbs: 44, fat: 20)
        ),
        Recipe(
            id: "quinoa_bowl",
            name: "Rainbow Quinoa Bowl",
            goal: .maintenance,
            emoji: "🌈",
            prepMinutes: 20,
            servings: 2,
            tags: ["Balanced", "Vegetarian", "Colorful"],
            ingredients: [
                Ingredient(amount: "150g", name: "Quinoa (dry)"),
                Ingredient(amount: "1/2", name: "Avocado, sliced"),
                Ingredient(amount: "1 cup", name: "Cherry tomatoes"),
                Ingredient(amount: "1 cup", name: "Cucumber, diced"),
                Ingredient(amount: "100g", name: "Chickpeas (canned, drained)"),
                Ingredient(amount: "2 tbsp", name: "Lemon-tahini dressing"),
            ],
            steps: [
                "Cook quinoa according to package (usually 2:1 water ratio, 15 min).",
                "Fluff quinoa with a fork and let cool slightly.",
                "Arrange quinoa in bowls and top with avocado, tomatoes, cucumber, and chickpeas.",
                "Drizzle with lemon-tahini dressing and serve.",
            ],
            nutrition: NutritionInfo(calories: 480, protein: 18, carbs: 62, fat: 16)
        ),
        Recipe(
            id: "avocado_eggs_toast",
            name: "Avocado & Eggs Toast",
            goal: .maintenance,
            emoji: "🥑",
            prepMinutes: 10,
            servings: 1,
            tags: ["Quick", "Breakfast", "Healthy Fats"],
            ingredients: [
                Ingredient(amount: "2 slices", name: "Whole wheat bread, toasted"),
                Ingredient(amount: "1 medium", name: "Avocado"),
                Ingredient(amount: "2 whole", name: "Eggs (poached or fried)"),
                Ingredient(amount: "1/4 tsp", name: "Chili flakes"),
                Ingredient(amount: "to taste", name: "Salt, pepper, lemon juice"),
            ],
            steps: [
                "Toast bread until golden.",
                "Mash avocado with salt, pepper, and a squeeze of lemon.",
                "Poach or fry eggs to your liking.",
                "Spread avocado over toast and top with eggs.",
                "Finish with chili flakes.",
            ],
            nutrition: NutritionInfo(calories: 440, protein: 20, carbs: 38, fat: 24)
        ),
        Recipe(
            id: "stir_fry_tofu",
            name: "Tofu Stir-Fry",
            goal: .maintenance,
            emoji: "🥦",
            prepMinutes: 20,
            servings: 2,
            tags: ["Vegetarian", "Quick", "Balanced"],
            ingredients: [
                Ingredient(amount: "250g", name: "Firm tofu, cubed"),
                Ingredient(amount: "1 cup", name: "Broccoli florets"),
                Ingredient(amount: "1 cup", name: "Bell pepper, sliced"),
                Ingredient(amount: "150g", name: "White rice (cooked)"),
                Ingredient(amount: "2 tbsp", name: "Soy sauce (low sodium)"),
                Ingredient(amount: "1 tbsp", name: "Sesame oil"),
                Ingredient(amount: "1 tsp", name: "Ginger, grated"),
            ],
            steps: [
                "Pat tofu dry and cut into cubes.",
                "Pan-fry tofu in sesame oil over high heat until golden on all sides, ~8 min.",
                "Add broccoli and bell pepper. Stir-fry 4 minutes.",
                "Add soy sauce and ginger. Toss for 1 minute.",
                "Serve over rice.",
            ],
            nutrition: NutritionInfo(calories: 420, protein: 22, carbs: 48, fat: 14)
        ),
        Recipe(
            id: "hummus_wrap",
            name: "Mediterranean Hummus Wrap",
            goal: .maintenance,
            emoji: "🌯",
            prepMinutes: 8,
            servings: 1,
            tags: ["Vegan", "Quick", "No Cook"],
            ingredients: [
                Ingredient(amount: "1 large", name: "Whole wheat tortilla"),
                Ingredient(amount: "4 tbsp", name: "Hummus"),
                Ingredient(amount: "1/2 cup", name: "Mixed greens"),
                Ingredient(amount: "1/4", name: "Cucumber, sliced"),
                Ingredient(amount: "1/4", name: "Red bell pepper, sliced"),
                Ingredient(amount: "2 tbsp", name: "Sun-dried tomatoes"),
                Ingredient(amount: "to taste", name: "Salt, pepper, oregano"),
            ],
            steps: [
                "Warm the tortilla in a dry pan for 30 seconds per side.",
                "Spread hummus evenly across the tortilla.",
                "Layer greens, cucumber, bell pepper, and sun-dried tomatoes.",
                "Season with salt, pepper, and oregano.",
                "Roll tightly and slice in half.",
            ],
            nutrition: NutritionInfo(calories: 380, protein: 14, carbs: 52, fat: 14)
        ),
        Recipe(
            id: "lentil_soup",
            name: "Hearty Lentil Soup",
            goal: .maintenance,
            emoji: "🍲",
            prepMinutes: 35,
            servings: 4,
            tags: ["Vegan", "Meal Prep", "Filling"],
            ingredients: [
                Ingredient(amount: "300g", name: "Red lentils, rinsed"),
                Ingredient(amount: "1 medium", name: "Onion, diced"),
                Ingredient(amount: "2 medium", name: "Carrots, diced"),
                Ingredient(amount: "2 cloves", name: "Garlic, minced"),
                Ingredient(amount: "1.5L", name: "Vegetable broth"),
                Ingredient(amount: "2 tbsp", name: "Olive oil"),
                Ingredient(amount: "1 tsp each", name: "Cumin, paprika, turmeric"),
            ],
            steps: [
                "Heat olive oil in a large pot over medium heat.",
                "Sauté onion, garlic, and carrots for 5 minutes until softened.",
                "Add spices and stir for 1 minute until fragrant.",
                "Add lentils and broth. Bring to a boil, then simmer 20-25 min.",
                "Stir occasionally until lentils are tender. Season and serve.",
            ],
            nutrition: NutritionInfo(calories: 320, protein: 18, carbs: 48, fat: 6)
        ),
        Recipe(
            id: "veggie_pasta",
            name: "Veggie Pasta Primavera",
            goal: .maintenance,
            emoji: "🍝",
            prepMinutes: 20,
            servings: 2,
            tags: ["Vegetarian", "Quick", "Colorful"],
            ingredients: [
                Ingredient(amount: "200g", name: "Whole wheat pasta"),
                Ingredient(amount: "1 cup", name: "Cherry tomatoes"),
                Ingredient(amount: "1 medium", name: "Zucchini, sliced"),
                Ingredient(amount: "1", name: "Red bell pepper, sliced"),
                Ingredient(amount: "3 tbsp", name: "Olive oil"),
                Ingredient(amount: "3 cloves", name: "Garlic, minced"),
                Ingredient(amount: "30g", name: "Parmesan, grated"),
            ],
            steps: [
                "Cook pasta according to package instructions.",
                "Meanwhile, heat olive oil in a large skillet over medium-high heat.",
                "Add garlic and sauté for 30 seconds.",
                "Add zucchini and bell pepper. Cook 4-5 min until tender-crisp.",
                "Toss in cherry tomatoes and cook 2 more minutes.",
                "Drain pasta and combine with vegetables. Top with parmesan.",
            ],
            nutrition: NutritionInfo(calories: 460, protein: 16, carbs: 68, fat: 14)
        ),
    ]

    // MARK: - Vegan / Vegetarian — additional options

    static let plantBased: [Recipe] = [
        Recipe(
            id: "lentil_power_bowl",
            name: "Lentil Power Bowl",
            goal: .muscleGain,
            emoji: "🥗",
            prepMinutes: 25,
            servings: 2,
            tags: ["Vegan", "High Protein", "Meal Prep"],
            ingredients: [
                Ingredient(amount: "200g", name: "Green lentils (cooked)"),
                Ingredient(amount: "150g", name: "Quinoa (cooked)"),
                Ingredient(amount: "1/2", name: "Avocado, sliced"),
                Ingredient(amount: "1 cup", name: "Roasted sweet potato"),
                Ingredient(amount: "1 cup", name: "Spinach"),
                Ingredient(amount: "2 tbsp", name: "Tahini"),
                Ingredient(amount: "1 tbsp", name: "Lemon juice"),
            ],
            steps: [
                "Roast cubed sweet potato at 200°C for 20 min until tender.",
                "Whisk tahini, lemon juice, and 2 tbsp water until smooth.",
                "Arrange quinoa and lentils at the base of each bowl.",
                "Top with sweet potato, avocado, and spinach.",
                "Drizzle with tahini sauce and serve.",
            ],
            nutrition: NutritionInfo(calories: 540, protein: 26, carbs: 72, fat: 18)
        ),
        Recipe(
            id: "black_bean_tacos",
            name: "Black Bean & Quinoa Tacos",
            goal: .muscleGain,
            emoji: "🌮",
            prepMinutes: 20,
            servings: 2,
            tags: ["Vegan", "High Protein", "Budget"],
            ingredients: [
                Ingredient(amount: "200g", name: "Black beans (canned, drained)"),
                Ingredient(amount: "100g", name: "Quinoa (cooked)"),
                Ingredient(amount: "6 small", name: "Corn tortillas"),
                Ingredient(amount: "1/2", name: "Avocado, sliced"),
                Ingredient(amount: "1/2 cup", name: "Salsa"),
                Ingredient(amount: "1/4 cup", name: "Fresh cilantro"),
                Ingredient(amount: "1 tsp each", name: "Cumin, chili powder"),
            ],
            steps: [
                "Heat black beans with cumin and chili powder in a pan, 5 minutes.",
                "Lightly toast tortillas in a dry pan, 30 sec per side.",
                "Mix beans with cooked quinoa.",
                "Fill each tortilla with the bean-quinoa mixture.",
                "Top with avocado, salsa, and cilantro.",
            ],
            nutrition: NutritionInfo(calories: 480, protein: 22, carbs: 68, fat: 12)
        ),
        Recipe(
            id: "tofu_buddha_bowl",
            name: "Tofu Buddha Bowl",
            goal: .weightLoss,
            emoji: "🥙",
            prepMinutes: 25,
            servings: 1,
            tags: ["Vegan", "Low Calorie", "Filling"],
            ingredients: [
                Ingredient(amount: "150g", name: "Firm tofu, cubed"),
                Ingredient(amount: "100g", name: "Brown rice (cooked)"),
                Ingredient(amount: "1 cup", name: "Roasted broccoli"),
                Ingredient(amount: "1/2", name: "Carrot, julienned"),
                Ingredient(amount: "1/4", name: "Red cabbage, shredded"),
                Ingredient(amount: "1 tbsp", name: "Soy sauce (low sodium)"),
                Ingredient(amount: "1 tsp", name: "Sesame oil"),
            ],
            steps: [
                "Press tofu, then pan-fry in sesame oil until golden, ~6 min.",
                "Toss tofu with soy sauce in the last minute.",
                "Arrange rice at the base of a bowl.",
                "Top with tofu, broccoli, carrot, and cabbage in sections.",
                "Drizzle with extra soy sauce or sriracha to taste.",
            ],
            nutrition: NutritionInfo(calories: 380, protein: 22, carbs: 42, fat: 14)
        ),
        Recipe(
            id: "chickpea_salad",
            name: "Greek Chickpea Salad",
            goal: .weightLoss,
            emoji: "🥗",
            prepMinutes: 10,
            servings: 2,
            tags: ["Vegan", "No Cook", "Quick"],
            ingredients: [
                Ingredient(amount: "200g", name: "Chickpeas (canned, drained)"),
                Ingredient(amount: "1 cup", name: "Cucumber, diced"),
                Ingredient(amount: "1 cup", name: "Cherry tomatoes, halved"),
                Ingredient(amount: "1/4", name: "Red onion, finely diced"),
                Ingredient(amount: "2 tbsp", name: "Olive oil"),
                Ingredient(amount: "1 tbsp", name: "Lemon juice"),
                Ingredient(amount: "1 tsp", name: "Dried oregano"),
            ],
            steps: [
                "In a large bowl, combine chickpeas, cucumber, tomatoes, and onion.",
                "Whisk olive oil, lemon juice, and oregano in a small bowl.",
                "Pour dressing over the salad and toss to combine.",
                "Season with salt and pepper.",
                "Refrigerate 10 min before serving for best flavor.",
            ],
            nutrition: NutritionInfo(calories: 280, protein: 12, carbs: 32, fat: 12)
        ),
        Recipe(
            id: "cauliflower_stir_fry",
            name: "Cauliflower Rice Stir-Fry",
            goal: .weightLoss,
            emoji: "🥦",
            prepMinutes: 15,
            servings: 2,
            tags: ["Vegan", "Low Carb", "Quick"],
            ingredients: [
                Ingredient(amount: "1 head", name: "Cauliflower, riced"),
                Ingredient(amount: "1 cup", name: "Mixed vegetables (peas, carrots, corn)"),
                Ingredient(amount: "2", name: "Eggs (omit for vegan)"),
                Ingredient(amount: "2 tbsp", name: "Soy sauce (low sodium)"),
                Ingredient(amount: "1 tbsp", name: "Sesame oil"),
                Ingredient(amount: "2 cloves", name: "Garlic, minced"),
                Ingredient(amount: "1 tsp", name: "Ginger, grated"),
            ],
            steps: [
                "Rice cauliflower in a food processor until rice-sized.",
                "Heat sesame oil in a large wok over high heat.",
                "Sauté garlic and ginger for 30 seconds.",
                "Add mixed vegetables and stir-fry 3 minutes.",
                "Add cauliflower rice and soy sauce. Stir-fry 5 more minutes.",
                "Serve hot, garnished with green onions if desired.",
            ],
            nutrition: NutritionInfo(calories: 220, protein: 10, carbs: 24, fat: 10)
        ),
        Recipe(
            id: "spinach_frittata",
            name: "Spinach & Mushroom Frittata",
            goal: .weightLoss,
            emoji: "🍳",
            prepMinutes: 20,
            servings: 2,
            tags: ["Vegetarian", "Low Carb", "High Protein"],
            ingredients: [
                Ingredient(amount: "6", name: "Eggs"),
                Ingredient(amount: "2 cups", name: "Fresh spinach"),
                Ingredient(amount: "1 cup", name: "Mushrooms, sliced"),
                Ingredient(amount: "1/4 cup", name: "Feta cheese, crumbled"),
                Ingredient(amount: "1 tbsp", name: "Olive oil"),
                Ingredient(amount: "to taste", name: "Salt, pepper, herbs"),
            ],
            steps: [
                "Preheat oven to 180°C.",
                "Heat olive oil in an oven-safe skillet over medium heat.",
                "Sauté mushrooms for 4 minutes until golden.",
                "Add spinach and cook until wilted, 1 minute.",
                "Beat eggs with salt and pepper. Pour over vegetables.",
                "Sprinkle feta on top. Bake 10-12 min until set.",
            ],
            nutrition: NutritionInfo(calories: 310, protein: 24, carbs: 6, fat: 22)
        ),
        Recipe(
            id: "cottage_cheese_bowl",
            name: "Cottage Cheese & Berry Bowl",
            goal: .muscleGain,
            emoji: "🫐",
            prepMinutes: 5,
            servings: 1,
            tags: ["Vegetarian", "High Protein", "No Cook"],
            ingredients: [
                Ingredient(amount: "200g", name: "Cottage cheese (low fat)"),
                Ingredient(amount: "1/2 cup", name: "Mixed berries"),
                Ingredient(amount: "30g", name: "Granola"),
                Ingredient(amount: "1 tbsp", name: "Almonds, slivered"),
                Ingredient(amount: "1 tsp", name: "Honey"),
                Ingredient(amount: "1/4 tsp", name: "Cinnamon"),
            ],
            steps: [
                "Place cottage cheese in a bowl.",
                "Top with mixed berries and granola.",
                "Sprinkle with slivered almonds and cinnamon.",
                "Drizzle with honey.",
                "Serve immediately for best texture.",
            ],
            nutrition: NutritionInfo(calories: 380, protein: 32, carbs: 38, fat: 10)
        ),
        Recipe(
            id: "avocado_quinoa_salad",
            name: "Avocado & Quinoa Salad",
            goal: .maintenance,
            emoji: "🥑",
            prepMinutes: 15,
            servings: 2,
            tags: ["Vegan", "Healthy Fats", "Balanced"],
            ingredients: [
                Ingredient(amount: "150g", name: "Quinoa (cooked)"),
                Ingredient(amount: "1", name: "Avocado, diced"),
                Ingredient(amount: "1 cup", name: "Cherry tomatoes, halved"),
                Ingredient(amount: "1/2", name: "Cucumber, diced"),
                Ingredient(amount: "1/4 cup", name: "Fresh parsley, chopped"),
                Ingredient(amount: "3 tbsp", name: "Olive oil"),
                Ingredient(amount: "2 tbsp", name: "Lemon juice"),
            ],
            steps: [
                "Let cooked quinoa cool to room temperature.",
                "In a large bowl, combine quinoa, avocado, tomatoes, cucumber, and parsley.",
                "Whisk olive oil and lemon juice in a small bowl.",
                "Pour dressing over salad and toss gently.",
                "Season with salt and pepper.",
            ],
            nutrition: NutritionInfo(calories: 420, protein: 12, carbs: 42, fat: 22)
        ),
    ]

}
